/**
 * Supabase Database Types
 *
 * This file will be auto-generated by Supabase CLI once you run:
 * supabase gen types typescript --local > lib/supabase/database.types.ts
 *
 * For now, I'll provide the basic types based on our planned schema
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      courses: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          language: string;
          style: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
          agent_ids: string[] | null;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          language?: string;
          style?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          agent_ids?: string[] | null;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          language?: string;
          style?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          agent_ids?: string[] | null;
          is_deleted?: boolean;
        };
      };
      scenes: {
        Row: {
          id: string;
          course_id: string;
          type: 'slide' | 'quiz' | 'interactive' | 'pbl';
          title: string;
          order: number;
          content: Json;
          actions: Json | null;
          whiteboard: Json | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          course_id: string;
          type: 'slide' | 'quiz' | 'interactive' | 'pbl';
          title: string;
          order: number;
          content: Json;
          actions?: Json | null;
          whiteboard?: Json | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          course_id?: string;
          type?: 'slide' | 'quiz' | 'interactive' | 'pbl';
          title?: string;
          order?: number;
          content?: Json;
          actions?: Json | null;
          whiteboard?: Json | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      chat_sessions: {
        Row: {
          id: string;
          course_id: string;
          type: 'qa' | 'discussion' | 'lecture';
          title: string;
          status: string;
          messages: Json;
          config: Json | null;
          tool_calls: Json | null;
          pending_tool_calls: Json | null;
          scene_id: string | null;
          last_action_index: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          course_id: string;
          type: 'qa' | 'discussion' | 'lecture';
          title: string;
          status?: string;
          messages: Json;
          config?: Json | null;
          tool_calls?: Json | null;
          pending_tool_calls?: Json | null;
          scene_id?: string | null;
          last_action_index?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          course_id?: string;
          type?: 'qa' | 'discussion' | 'lecture';
          title?: string;
          status?: string;
          messages?: Json;
          config?: Json | null;
          tool_calls?: Json | null;
          pending_tool_calls?: Json | null;
          scene_id?: string | null;
          last_action_index?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      media_files: {
        Row: {
          id: string;
          course_id: string;
          element_id: string;
          type: 'image' | 'video';
          storage_path: string;
          mime_type: string;
          size_bytes: number | null;
          prompt: string | null;
          generation_params: Json | null;
          error: string | null;
          error_code: string | null;
          poster_path: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          course_id: string;
          element_id: string;
          type: 'image' | 'video';
          storage_path: string;
          mime_type: string;
          size_bytes?: number | null;
          prompt?: string | null;
          generation_params?: Json | null;
          error?: string | null;
          error_code?: string | null;
          poster_path?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          course_id?: string;
          element_id?: string;
          type?: 'image' | 'video';
          storage_path?: string;
          mime_type?: string;
          size_bytes?: number | null;
          prompt?: string | null;
          generation_params?: Json | null;
          error?: string | null;
          error_code?: string | null;
          poster_path?: string | null;
          created_at?: string;
        };
      };
      generated_agents: {
        Row: {
          id: string;
          course_id: string;
          name: string;
          role: 'teacher' | 'assistant' | 'student';
          persona: string | null;
          avatar: string | null;
          color: string | null;
          priority: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          course_id: string;
          name: string;
          role: 'teacher' | 'assistant' | 'student';
          persona?: string | null;
          avatar?: string | null;
          color?: string | null;
          priority?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          course_id?: string;
          name?: string;
          role?: 'teacher' | 'assistant' | 'student';
          persona?: string | null;
          avatar?: string | null;
          color?: string | null;
          priority?: number;
          created_at?: string;
        };
      };
      audio_files: {
        Row: {
          id: string;
          course_id: string;
          storage_path: string;
          duration_seconds: number | null;
          format: string;
          text: string | null;
          voice: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          course_id: string;
          storage_path: string;
          duration_seconds?: number | null;
          format?: string;
          text?: string | null;
          voice?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          course_id?: string;
          storage_path?: string;
          duration_seconds?: number | null;
          format?: string;
          text?: string | null;
          voice?: string | null;
          created_at?: string;
        };
      };
      playback_state: {
        Row: {
          course_id: string;
          scene_index: number;
          action_index: number;
          consumed_discussions: string[] | null;
          updated_at: string;
        };
        Insert: {
          course_id: string;
          scene_index?: number;
          action_index?: number;
          consumed_discussions?: string[] | null;
          updated_at?: string;
        };
        Update: {
          course_id?: string;
          scene_index?: number;
          action_index?: number;
          consumed_discussions?: string[] | null;
          updated_at?: string;
        };
      };
      stage_outlines: {
        Row: {
          course_id: string;
          outlines: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          course_id: string;
          outlines: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          course_id?: string;
          outlines?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
